language: objective-c

before_install: "git submodule init && git submodule update"
script: xctool -project TravisTestTest.xcodeproj -scheme TravisTestTest -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=NO clean test

