language: objective-c

before_install: "git submodule init && git submodule update"
script: xctool -project TravisTestTest.xcodeproj -scheme TravisTestTestTests test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

